[workspace]
resolver = "2"
members = [ "crates/arch-x86_64", "crates/hadron-test", "crates/kernel-base", "crates/limine", "crates/menuconfig", "crates/volatile","kernel"]
default-members = ["kernel"]

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
menuconfig = { path = "crates/menuconfig", default-features = false }
limine = { path = "crates/limine", default-features = false }
volatile = { path = "crates/volatile", default-features = false }
kernel-base = { path = "crates/kernel-base", default-features = false }
arch-x86_64 = { path = "crates/arch-x86_64", default-features = false }
hadron-test = { path = "crates/hadron-test", default-features = false }

static_assertions = { version = "1.1.0", features = ["nightly"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
