[package]
name = "hadron-device"
version.workspace = true
edition.workspace = true

[dependencies]
hadron-base.workspace = true

x86_64.workspace = true
log.workspace = true
bitflags.workspace = true
