# Kernel configuration

[option.debug]
description = "Enable debug"
depends = []
type = "bool"
default = false

[option.serial]
description = "Enable kernel printk serial output"
depends = []
type = "bool"
default = false

[option.backtrace]
description = "Enable kernel backtrace"
depends = []
type = "bool"
default = false

[option.smp]
description = "Enable SMP"
depends = []
type = "bool"
default = false
