[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "targets/x86_64-unknown-hadron.json"

[target.x86_64-unknown-hadron]
runner = "cargo qemu-runner"
rustflags = [
    "-Cforce-unwind-tables",
]
