[package]
name = "hadron-kernel"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "hadron-kernel"
path = "src/main.rs"
test = false
bench = false

[features]
default = []
# Enables the serial port driver
printk_serial = []

[dependencies]
hadron-base.workspace = true
hadron-device.workspace = true
hadron-drivers.workspace = true

spin.workspace = true
log.workspace = true
limine.workspace = true
x86_64.workspace = true
tracing.workspace = true

linked_list_allocator = "0.10.5"

[dev-dependencies]
limine = { workspace = true, features = ["internal-api"] }
static_assertions.workspace = true
hadron-test.workspace = true

