[package]
name = "kernel-boot"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
limine.workspace = true
kernel-base.workspace = true
log.workspace = true
